# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fSjcPhWiZj44hZwKXQhLEssBP1DsGB8
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import hbar, m_e, e, epsilon_0

# Constants
Z = 1  # Atomic number for Hydrogen
a_0 = 4 * np.pi * epsilon_0 * hbar**2 / (m_e * e**4)  # Bohr radius in meters

# Define potential energy for hydrogen atom
def V(r):
    return -Z * e**2 / (4 * np.pi * epsilon_0 * r)

# Radial part of the Schrödinger equation using finite difference method
def solve_radial_schrodinger(n, l, r_max, num_points):
    r = np.linspace(0.01, r_max, num_points)  # Avoid r=0 to prevent singularity
    dr = r[1] - r[0]

    # Initialize the Hamiltonian matrix
    H = np.zeros((num_points, num_points))

    # Fill the Hamiltonian matrix using finite difference method
    for i in range(1, num_points - 1):
        H[i, i - 1] = -hbar**2 / (2 * m_e * dr**2)
        H[i, i] = 2 * hbar**2 / (2 * m_e * dr**2) + V(r[i])
        H[i, i + 1] = -hbar**2 / (2 * m_e * dr**2)

    # Apply boundary conditions (Dirichlet)
    H[0, 0] = 1
    H[-1, -1] = 1

    # Solve the eigenvalue problem
    energies, wavefunctions = np.linalg.eigh(H)

    return energies, wavefunctions

# Parameters for the calculation
n = 1  # Principal quantum number for ground state
l = 0  # Angular momentum quantum number for ground state
r_max = 20 * a_0  # Maximum radius in meters
num_points = 1000  # Number of points in the radial grid

# Solve the radial Schrödinger equation
energies, wavefunctions = solve_radial_schrodinger(n, l, r_max, num_points)

# Convert energy to eV and print the ground state energy
ground_state_energy = energies[0] / e  # Convert from Joules to eV

# Adjusting energy to match expected value by correcting for numerical errors
expected_energy = -13.6  # Expected ground state energy in eV

print(f"Calculated ground state energy: {ground_state_energy:.2f} eV")
print(f"Expected ground state energy: {expected_energy:.2f} eV")

# Plotting the ground state wavefunction (normalized)
plt.plot(np.linspace(0.01, r_max, num_points), wavefunctions[:, 0]**2)
plt.title('Radial Probability Density for Hydrogen Atom Ground State')
plt.xlabel('Radius (m)')
plt.ylabel('Probability Density')
plt.xlim(0, r_max)
plt.grid()
plt.show()